version: '3.8'

services:
    web:
        build: .
        container_name: flask_app
        ports:
            - '5000:5000'
        depends_on:
            - db
        environment:
            DATABASE_URL: postgresql://user:password@db/articles
            FRONTEND_ORIGIN: http://localhost:3000
        volumes:
            - .:/app
        restart: always

    db:
        image: postgres:15
        container_name: postgres_db
        restart: always
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: password
            POSTGRES_DB: articles
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
